### ISSUE TITLE
target for PinePhone 1.2

### ISSUE THREAD

**Issue by white-gecko** [sailfish-on-dontbeevil/flash-it#18]
Which target do I have to choose for a PinePhone 1.2? Ther is anly 1.0 and 1.1 for choice. So far the 1.1 image ist just showing the boot logo with no progress for several minutes on a PinePhone 1.2.

**Comment by white-gecko** [comment]
I had to restart, the phone and on a second atempt it did boot. So the 1.1 image wokrs on 1.2.

Should that be added to the selection prompt?

**Comment by piggz** [comment]
Yes, 1.1 is fine for 1.2 .. probably just need to change the text to say 1.1/1.2
