### ISSUE TITLE
Update Sailfish OS version on pinephone pro?

### ISSUE THREAD

**Issue by bdodroid** [sailfish-on-dontbeevil/flash-it#33]
Sorry if this is the wrong place, this is more of a question about updating.

Is updating the SailfishOS version via command line on pinephone pro supported/recommended? 

I was messing around with the system on my phone and switched the version to 4.4.0.72, ran version -dup, and noticed it pulled in some pinephonepro specific packages and I was just curious what the normal flow of updating sailfish on pinephone pro is supposed to be, if at all. 

Is it better to stay at 4.3 for now? Will I get an OTA update when pinephone pro is ready for an update?

Updating the pinephone pro to 4.4 actually fixed a missing amber-mpris issue I was having and allowed me to actually add my google account to the system. 

The only downside I have seen so far is the tap to wake no longer seems to work, and waydroid still gives me the "binder_linux" not found error.

**Comment by piggz** [comment]
Hi, no, you are best off on 4.4.  I will add update instructions to the new Wiki ive set up here https://github.com/sailfish-on-dontbeevil/documentation/wiki/

You will not get OTA update notifications, but you can update on the command line, or using sfos-upgrade app from storeman.

Kernel specific issues like the binder one could be logged against the kernel package, there is a package for the regular and pro kernels.

Thanks
