### ISSUE TITLE
/dev/sdX partitions are not referenced correctly 

### ISSUE THREAD

**Issue by thrrgilag** [sailfish-on-dontbeevil/flash-it#5]
This condition check always returns true regardless of the value stored in DEVICE_NODE

https://github.com/sailfish-on-dontbeevil/flash-it/blob/c1c656b1a6f7f428e3879c862de758bf53e4eaf7/flash-it.sh#L198

**Comment by depsterr** [comment]
I've sent in a pull request to fix this issue #7 

I would appreciate it if you could try running [the script from my fork](https://raw.githubusercontent.com/depsterr/flash-it/master/flash-it.sh) to make sure it is working for you too.
